Idmcu: 3
Namespace: "demo"
Port: "/dev/ttyACM0"
generate_library_Path: "arduino/libraries"
Baudrate: 57600
Setup_Publisher:  [                           ]
Setup_Subscriber: [                           ]
Setup_Srv_client: [                           ]
Setup_Srv_server: [                           ]
Setup_Action_client: [                        ]
Setup_Action_server: [                        ]

 
